version: '2'
services:
  web:
    build: .
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - ./platform:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=127.0.0.1"
      PHP_IDE_CONFIG: "serverName=Test"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: develop
     MYSQL_PASSWORD: develop123
     MYSQL_DATABASE: develop